import contextlib
import math
import os
import re
import shutil
import subprocess
import tempfile
import uuid
from typing import List, Optional, Sequence, Tuple


class FFmpegNotFound(Exception):
    pass


class FFmpegError(Exception):
    pass


def find_ffmpeg() -> str:
    path = os.environ.get("FFMPEG_PATH") or shutil.which("ffmpeg")
    if not path:
        raise FFmpegNotFound("ffmpeg not found: install it or set FFMPEG_PATH")
    return path


# D12 (editing.md E8, YouTube's official upload settings): BT.709 colour tags + the index at the front of the file (faststart: the
# platform / a phone can start playing before the whole file is read). 24 fps stays: every clip of the pipeline is made at 24.
# a still picture (RGB) made into video: convert with the BT.709 matrix the files are tagged with — measured 2026-09-26, an end card
# converted by the default scaler inside a filter graph got BT.601 numbers under a BT.709 tag (pure red Y 81 instead of 63)
TO_YUV709 = "scale=out_color_matrix=bt709:out_range=tv,format=yuv420p"
# editing.md E8: one quality for every step of the cut — video CRF 18 (x264 default was 23), AAC 256 kbps (default ~128). The cut is
# encoded several times (join → music → extras → loudness), so each audio generation is kept well above YouTube's 128 kbps floor.
AAC = ["-c:a", "aac", "-b:a", "256k"]
PCM = ["-c:a", "pcm_s16le"]      # between two mixing steps (TON_DONG A18): the sound is encoded to AAC once, at the last step
LOOP_XFADE = 1.5                 # music shorter than the film: it plays again from the start, crossfaded over this many seconds
COLOR_TAGS = ["-colorspace", "bt709", "-color_primaries", "bt709", "-color_trc", "bt709"]
_ENCODE = ["-c:v", "libx264", "-crf", "18", "-pix_fmt", "yuv420p", "-r", "24", "-colorspace", "bt709", "-color_primaries", "bt709",
           "-color_trc", "bt709", "-movflags", "+faststart"]


def write_concat_list(clips: Sequence[str], directory: Optional[str] = None) -> str:
    fd, path = tempfile.mkstemp(suffix=".txt", dir=directory)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        for clip in clips:
            escaped = os.path.abspath(clip).replace("\\", "/").replace("'", "'\\''")
            f.write(f"file '{escaped}'\n")
    return path


def build_concat_cmd(list_file: str, output: str, ffmpeg: str = "ffmpeg") -> List[str]:
    return [ffmpeg, "-y", "-f", "concat", "-safe", "0", "-i", list_file, *_ENCODE, "-an", output]


OVERLAP_STYLES = {"crossfade": "fade", "dip_to_black": "fadeblack"}


_A_NORM = "aformat=sample_rates=48000:channel_layouts=stereo"  # clips from a model may differ in audio format


def _fit(size, mode: str = "pad") -> str:
    """Filter that brings any clip to exactly W x H: 'pad' keeps the whole picture (bars), 'crop' fills the frame."""
    w, h = int(size[0]) // 2 * 2, int(size[1]) // 2 * 2
    if mode == "crop":
        return f"scale={w}:{h}:force_original_aspect_ratio=increase,crop={w}:{h},setsar=1,fps=24"
    return f"scale={w}:{h}:force_original_aspect_ratio=decrease,pad={w}:{h}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=24"


def build_concat_scaled_cmd(clips: Sequence[str], output: str, size, ffmpeg: str = "ffmpeg") -> List[str]:
    """Hard cut without sound where clips may differ in size (e.g. two video models in one project): each clip is brought to
    the project frame first (the concat demuxer would break on mixed sizes)."""
    if not clips:
        raise ValueError("no clips")
    cmd = [ffmpeg, "-y"]
    parts = []
    for i, clip in enumerate(clips):
        cmd += ["-i", clip]
        parts.append(f"[{i}:v]{_fit(size)}[v{i}]")
    parts.append("".join(f"[v{i}]" for i in range(len(clips))) + f"concat=n={len(clips)}:v=1:a=0[v]")
    return cmd + ["-filter_complex", ";".join(parts), "-map", "[v]", *_ENCODE, "-an", output]


def build_concat_audio_cmd(clips: Sequence[str], output: str, ffmpeg: str = "ffmpeg", size=None) -> List[str]:
    """Hard cut that KEEPS each clip's own audio (e.g. dialogue generated by the video model). Every clip needs an
    audio stream. `size`: bring every clip to this frame first."""
    if not clips:
        raise ValueError("no clips")
    cmd = [ffmpeg, "-y"]
    parts = []
    for i, clip in enumerate(clips):
        cmd += ["-i", clip]
        parts.append(f"[{i}:v]{_fit(size) if size else 'setsar=1'}[v{i}];[{i}:a]{_A_NORM}[a{i}]")
    joined = "".join(f"[v{i}][a{i}]" for i in range(len(clips)))
    parts.append(f"{joined}concat=n={len(clips)}:v=1:a=1[v][a]")
    return cmd + ["-filter_complex", ";".join(parts), "-map", "[v]", "-map", "[a]", *_ENCODE, *AAC, output]


def build_crossfade_cmd(clips: Sequence[str], durations: Sequence[float], output: str,
                        fade: float = 1.0, ffmpeg: str = "ffmpeg", style: str = "fade",
                        with_audio: bool = False, size=None) -> List[str]:
    if len(clips) != len(durations) or len(clips) < 2:
        raise ValueError("need >= 2 clips and one duration per clip")
    if any(d <= fade for d in durations):
        raise ValueError("every clip must be longer than the crossfade")
    cmd = [ffmpeg, "-y"]
    for clip in clips:
        cmd += ["-i", clip]
    parts = [f"[{i}:v]{_fit(size)}[s{i}]" for i in range(len(clips))] if size else []
    src = (lambda i: f"[s{i}]") if size else (lambda i: f"[{i}:v]")
    prev, elapsed = src(0), durations[0]
    for i in range(1, len(clips)):
        offset = round(elapsed - fade, 3)
        label = f"[v{i}]"
        parts.append(f"{prev}{src(i)}xfade=transition={style}:duration={fade}:offset={offset}{label}")
        prev = label
        elapsed += durations[i] - fade
    if not with_audio:
        return cmd + ["-filter_complex", ";".join(parts), "-map", prev, *_ENCODE, "-an", output]
    for i in range(len(clips)):
        parts.append(f"[{i}:a]{_A_NORM}[n{i}]")
    prev_a = "[n0]"
    for i in range(1, len(clips)):
        parts.append(f"{prev_a}[n{i}]acrossfade=d={fade}[x{i}]")
        prev_a = f"[x{i}]"
    return cmd + ["-filter_complex", ";".join(parts), "-map", prev, "-map", prev_a, *_ENCODE, *AAC, output]


# Trial 2A (2026-09-25): voices laid over the clips peaked at 0,0 dBFS (clipping on some phones) — every mix ends in a limiter at
# -2 dBFS (linear 0.794): the AAC encode after it overshoots ~0.8 dB, so -1 dBFS in the limiter came out at -0.2 dBFS.
PEAK_LIMIT = "alimiter=limit=0.794:level=false"


BREATH_S, BREATH_LEVEL = 0.6, 0.05     # D6 (editing.md E4): the music drops to ~-26 dB this long before a turn, so the hit lands


SHAKE_S, SHAKE_PX = 0.25, 10          # D9 (editing.md E6): a hit shakes the frame ~6 frames, up to 10 px, dying away


def shake_filter(times: Sequence[float]) -> str:
    """Crop-based camera shake at each time (the frame is enlarged 2 % so the shake never shows a border), decaying to rest."""
    if not times:
        return ""
    amp = "+".join(f"between(t,{x:.2f},{x + SHAKE_S:.2f})*(1-(t-{x:.2f})/{SHAKE_S})" for x in times)
    return (f"scale=iw*1.02:ih*1.02,crop=w=iw/1.02:h=ih/1.02:"
            f"x='(iw-iw/1.02)/2+{SHAKE_PX}*({amp})*sin(t*90)':y='(ih-ih/1.02)/2+{SHAKE_PX}*({amp})*cos(t*77)'")


def add_shake(src: str, dst: str, times: Sequence[float], ffmpeg: Optional[str] = None) -> str:
    ff = ffmpeg or find_ffmpeg()
    w, h = probe_size(src) or (1080, 1920)
    run([ff, "-y", "-i", src, "-vf", shake_filter(times) + f",scale={w}:{h}", *_ENCODE, "-c:a", "copy", dst])   # the exact frame back
    return dst


PULSE_S, PULSE_ZOOM, PULSE_PX = 0.35, 0.03, 4    # 07/10 (Khủng Long Đỏ): on each beat the frame punches in 3 % and shakes ~4 px, easing out


def music_beats(path: str, start: float = 0.0, until: Optional[float] = None) -> List[float]:
    """The beats of a music file (librosa beat tracker, DSP — no model) on the FILM's timeline: + `start` (the second the music comes
    in), only those before `until`."""
    import tempfile
    import librosa
    with tempfile.TemporaryDirectory() as d:      # 07/10: librosa (soundfile) cannot open .m4a — decode with ffmpeg first
        wav = os.path.join(d, "beats.wav")
        run([find_ffmpeg(), "-y", "-loglevel", "error", "-i", path, "-ac", "1", "-ar", "22050", wav])
        y, sr = librosa.load(wav, sr=22050, mono=True)
    _, frames = librosa.beat.beat_track(y=y, sr=sr)
    times = [round(float(t) + float(start or 0), 3) for t in librosa.frames_to_time(frames, sr=sr)]
    return [t for t in times if until is None or t < until - PULSE_S]


def pulse_filter(beats: Sequence[float], w: int, h: int) -> str:
    """A slight zoom punch + shake on each beat: the frame is scaled up by the beat's envelope (per frame) and cut back to w×h around the
    centre, so no border ever shows. Envelope (1-(t-b)/PULSE_S)^2: in at once, easing out."""
    if not beats:
        return ""
    env = "+".join(f"between(t,{b:.3f},{b + PULSE_S:.3f})*pow(1-(t-{b:.3f})/{PULSE_S},2)" for b in beats)
    return (f"scale=w='trunc({w}*(1+{PULSE_ZOOM}*({env}))/2)*2':h='trunc({h}*(1+{PULSE_ZOOM}*({env}))/2)*2':eval=frame,"
            f"crop={w}:{h}:x='(iw-{w})/2+{PULSE_PX}*({env})*sin(t*83)':y='(ih-{h})/2+{PULSE_PX}*({env})*cos(t*71)'")


def add_pulse(src: str, dst: str, beats: Sequence[float], ffmpeg: Optional[str] = None) -> str:
    ff = ffmpeg or find_ffmpeg()
    w, h = probe_size(src) or (1080, 1920)
    run([ff, "-y", "-i", src, "-vf", pulse_filter(beats, w, h), *_ENCODE, "-c:a", "copy", dst])
    return dst


FLASHBACK_FLASH = 0.25          # white flash in and out of a flashback shot (seconds)
FLASHBACK_LOOK = "eq=saturation=0.55:gamma=1.05,colorbalance=rs=0.08:gs=0.03:bs=-0.08:rm=0.06:bm=-0.06,vignette=angle=PI/4.5"


def flashback_filter(seconds: float) -> str:
    """The memory look of a flashback shot (trial #8, 2026-09-28): warm, washed-out colour, darker edges, a white flash in and out."""
    out_at = max(seconds - FLASHBACK_FLASH, 0.0)
    return (f"{FLASHBACK_LOOK},fade=t=in:st=0:d={FLASHBACK_FLASH}:color=white,"
            f"fade=t=out:st={out_at:.2f}:d={FLASHBACK_FLASH}:color=white")


# S3.6 (kế hoạch sau #8): a transition of its own at each cut, drawn INSIDE the two clips so the film's length never changes (voices,
# subtitles and effects stay where they were placed). cut / match / occlusion / j_cut / l_cut stay plain cuts here — an occlusion is
# designed in the shots' movement (dp.md Q12), a J/L cut is the sound's (flag j_cut).
EDGE_TRANSITIONS = ("flash", "dip", "whip", "zoom_through")
EDGE_S = {"flash": (0.10, 0.20), "dip": (0.25, 0.25), "whip": (0.15, 0.15), "zoom_through": (0.20, 0.20)}   # (tail of A, head of B)


def edge_filter(seconds: float, head: Optional[str] = None, tail: Optional[str] = None, size=None) -> Optional[str]:
    """Video filter for one clip: its own transition at its head and the next shot's at its tail. None when nothing changes.
    zoom_through needs the clip's `size` (W, H): zoompan redraws each frame (crop's width is set once, it cannot grow — tried)."""
    parts, zoom, d = [], [], max(float(seconds), 0.3)
    if tail in EDGE_TRANSITIONS:
        t = min(EDGE_S[tail][0], d / 3)
        st = round(d - t, 3)
        if tail in ("flash", "dip"):
            parts.append(f"fade=t=out:st={st}:d={t}:color={'white' if tail == 'flash' else 'black'}")
        elif tail == "whip":
            parts.append(f"boxblur=luma_radius=24:luma_power=2:chroma_radius=12:enable='gte(t,{st})'")
        else:
            zoom.append(f"if(gte(it,{st}),1+0.6*(it-{st})/{t},1)")
    if head in EDGE_TRANSITIONS:
        t = min(EDGE_S[head][1], d / 3)
        if head in ("flash", "dip"):
            parts.append(f"fade=t=in:st=0:d={t}:color={'white' if head == 'flash' else 'black'}")
        elif head == "whip":
            parts.append(f"boxblur=luma_radius=24:luma_power=2:chroma_radius=12:enable='lt(t,{t})'")
        else:
            zoom.append(f"if(lt(it,{t}),1.6-0.6*it/{t},1)")
    if zoom and size:
        w, h = int(size[0]) // 2 * 2, int(size[1]) // 2 * 2
        z = "*".join(f"({x})" for x in zoom)
        parts.insert(0, f"zoompan=z='{z}':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:s={w}x{h}:fps=24")
    return ",".join(parts) or None


def add_edges(src: str, dst: str, seconds: float, head: Optional[str], tail: Optional[str], ffmpeg: Optional[str] = None) -> Optional[str]:
    vf = edge_filter(seconds, head, tail, probe_size(src))
    if vf is None:
        return None
    ff = ffmpeg or find_ffmpeg()
    run([ff, "-y", "-i", src, "-vf", vf, *_ENCODE, "-c:a", "copy", dst])
    return dst


def add_flashback(src: str, dst: str, seconds: Optional[float] = None, ffmpeg: Optional[str] = None) -> str:
    ff = ffmpeg or find_ffmpeg()
    seconds = seconds or probe_duration(src) or 3.0
    run([ff, "-y", "-i", src, "-vf", flashback_filter(seconds), *_ENCODE, "-c:a", "copy", dst])
    return dst


def trim_head(src: str, dst: str, seconds: float, ffmpeg: Optional[str] = None) -> str:
    """The first `seconds` of the clip, re-encoded (frame accurate; the sound cut with it). The concat of a cut with plain `transition=cut`
    uses the whole file, so a shot made shorter in the edit needs its own shorter copy."""
    ff = ffmpeg or find_ffmpeg()
    cmd = [ff, "-y", "-i", src, "-t", f"{seconds:.2f}", *_ENCODE]
    if has_audio(src):
        cmd += AAC
    run(cmd + [dst])
    return dst


def skip_head(src: str, dst: str, seconds: float, keep: Optional[float] = None, ffmpeg: Optional[str] = None) -> str:
    """KLD-19: the clip WITHOUT its first `seconds` (then at most `keep` seconds), re-encoded — frame accurate, the sound cut with it
    (#22: the join 254 → 255 jerked at 1,5 s of 255; trim_head above keeps the beginning, this drops it)."""
    ff = ffmpeg or find_ffmpeg()
    cmd = [ff, "-y", "-i", src, "-ss", f"{seconds:.2f}"] + (["-t", f"{keep:.2f}"] if keep else []) + [*_ENCODE]
    if has_audio(src):
        cmd += AAC
    run(cmd + [dst])
    return dst


CUT_AUDIO_FADE_S = 0.02     # a few ms of fade at each side of the join: no click where the waveform is cut


def cut_segment(src: str, dst: str, start: float, end: float, cover: Optional[str] = None, ffmpeg: Optional[str] = None) -> str:
    """TODO điểm 12: the clip WITHOUT its `start`–`end` seconds (a bad stretch in the middle), re-encoded — frame accurate, the sound cut
    with it. `cover`: one of EDGE_TRANSITIONS drawn at the join (tail of the first half, head of the second, as at a cut between two
    shots), "shake" = the frame shakes where the halves meet; anything else = a plain cut. Raises ValueError for a stretch not inside."""
    have = probe_duration(src)
    if not have or not 0 < start < end < have:
        raise ValueError(f"đoạn {start:g}–{end:g} s không nằm trong clip ({have or 0:.2f} s)")
    ff = ffmpeg or find_ffmpeg()
    first, second = round(start, 3), round(have - end, 3)
    size = probe_size(src) if cover in ("zoom_through", "shake") else None      # zoompan / the shake's crop need the frame's size
    tail = edge_filter(first, tail=cover, size=size) if cover in EDGE_TRANSITIONS else None
    head = edge_filter(second, head=cover, size=size) if cover in EDGE_TRANSITIONS else None
    v = [f"[0:v]trim=start=0:end={start:.3f},setpts=PTS-STARTPTS{',' + tail if tail else ''}[v0]",
         f"[0:v]trim=start={end:.3f},setpts=PTS-STARTPTS{',' + head if head else ''}[v1]"]
    audio = has_audio(src)
    if audio:
        fd = CUT_AUDIO_FADE_S
        v += [f"[0:a]atrim=start=0:end={start:.3f},asetpts=PTS-STARTPTS,afade=t=out:st={max(start - fd, 0):.3f}:d={fd}[a0]",
              f"[0:a]atrim=start={end:.3f},asetpts=PTS-STARTPTS,afade=t=in:st=0:d={fd}[a1]",
              "[v0][a0][v1][a1]concat=n=2:v=1:a=1[vc][ac]"]
    else:
        v.append("[v0][v1]concat=n=2:v=1:a=0[vc]")
    if cover == "shake":
        w, h = size or (1080, 1920)
        v.append(f"[vc]{shake_filter([start])},scale={w}:{h}[vo]")
    else:
        v.append("[vc]null[vo]")
    cmd = [ff, "-y", "-i", src, "-filter_complex", ";".join(v), "-map", "[vo]"] + (["-map", "[ac]", *AAC] if audio else []) + [*_ENCODE, dst]
    run(cmd)
    return dst


def hold_last_frame(src: str, dst: str, extra: float, ffmpeg: Optional[str] = None) -> str:
    """The clip followed by its own last frame for `extra` seconds (sound padded with silence)."""
    ff = ffmpeg or find_ffmpeg()
    cmd = [ff, "-y", "-i", src, "-vf", f"tpad=stop_mode=clone:stop_duration={extra:.2f}", *_ENCODE]
    if has_audio(src):
        cmd += ["-af", f"apad=pad_dur={extra:.2f}", *AAC]
    run(cmd + [dst])
    return dst


# Music automation (trial #8 re-render, người dùng 2026-09-28: "nhạc vào không hợp lý, không có độ mềm mại"): the music used to switch
# off and on at full level in one audio frame. Now every change is a ramp, and a long Director "cut" becomes a silence that the music
# creeps back into softly: out in OFF_FADE s, silent for OFF_HOLD s (the line lands in silence), back at OFF_LOW (≈ −15 dB) over OFF_RISE s,
# and to full level over IN_FADE s once the silence ends.
OFF_FADE, OFF_HOLD, OFF_RISE, OFF_LOW, IN_FADE = 0.6, 4.0, 2.0, 0.18, 1.5
BREATH_FADE = 0.2


def _envelope_parts(times: Sequence[float], off: Sequence[Tuple[float, float]]) -> List[List[Tuple[float, float]]]:
    """Each silence / breath as its own piecewise-linear gain curve [(t, gain)], 1 outside its points."""
    parts = []
    for a, b in off:
        a, b = float(a), float(b)
        pts = [(max(a - OFF_FADE, 0.0), 1.0), (a, 0.0)]
        if b - a > OFF_HOLD + OFF_RISE:
            pts += [(a + OFF_HOLD, 0.0), (a + OFF_HOLD + OFF_RISE, OFF_LOW), (b, OFF_LOW)]
        else:
            pts += [(b, 0.0)]
        pts += [(pts[-1][0] + IN_FADE, 1.0)]
        parts.append(pts)
    for x in times:
        x = float(x)
        start = max(x - BREATH_S, 0.0)
        parts.append([(max(start - BREATH_FADE, 0.0), 1.0), (start, BREATH_LEVEL), (x, BREATH_LEVEL), (x + 0.05, 1.0)])
    return parts


def _gain_at(pts: List[Tuple[float, float]], t: float) -> float:
    if t <= pts[0][0] or t >= pts[-1][0]:          # every curve starts and ends at full level
        return 1.0
    for (t0, g0), (t1, g1) in zip(pts, pts[1:]):
        if t0 <= t <= t1:
            return g0 if t1 == t0 else g0 + (g1 - g0) * (t - t0) / (t1 - t0)
    return 1.0


def music_envelope(times: Sequence[float], off: Sequence[Tuple[float, float]] = ()) -> List[Tuple[float, float]]:
    """The music's gain over time as key points [(t, gain)] (the lowest of every silence / breath curve at each point)."""
    parts = _envelope_parts(times, off)
    keys = sorted({round(t, 3) for pts in parts for t, _ in pts})
    return [(t, round(min(_gain_at(pts, t) for pts in parts), 4)) for t in keys]


def breath_filter(times: Sequence[float], off: Sequence[Tuple[float, float]] = ()) -> str:
    """volume automation from music_envelope: breaths (near-silence in the BREATH_S before a turn, the music back on the turn itself) and
    the Director's silences (`cut` … `in`, core/sound_intent.py) — every change a ramp, never a click."""
    env = music_envelope(times, off)
    if not env:
        return ""
    terms = [f"between(t,{t0:.3f},{t1:.3f})*({g0:g}+({g1 - g0:g})*(t-{t0:.3f})/{max(t1 - t0, 1e-3):.3f})"
             for (t0, g0), (t1, g1) in zip(env, env[1:])]
    outside = f"(lt(t,{env[0][0]:.3f})+gt(t,{env[-1][0]:.3f}))*1"
    return f",volume='min(1,{outside}+{'+'.join(terms)})':eval=frame"


def music_loops(music_len: Optional[float], video_duration: float) -> int:
    """How many extra plays of the track fill the film (0 = the track is long enough, or its length is unknown)."""
    if not music_len or music_len <= LOOP_XFADE * 2 or music_len >= video_duration - 0.5:
        return 0
    return int(math.ceil((video_duration - music_len) / (music_len - LOOP_XFADE)))


def build_mux_music_cmd(video: str, music: str, output: str, video_duration: float,
                        fade: float = 1.5, volume: float = 0.6, ffmpeg: str = "ffmpeg",
                        has_audio: bool = False, breaths: Sequence[float] = (),
                        music_off: Sequence[Tuple[float, float]] = (), music_len: Optional[float] = None,
                        audio_codec: Sequence[str] = AAC, start: float = 0.0, end: Optional[float] = None) -> List[str]:
    """Music under the video. has_audio: the video already carries sound (dialogue): the music is MIXED with it
    instead of replacing it. breaths: turn times with a short silence before them (D6). music_len: the track's length — a track
    shorter than the film plays again from the start, crossfaded (trial #8, 2026-09-28: 68 s of music under 83 s of film = the last
    15 s silent). audio_codec: PCM when another mixing step follows (one AAC encode only). start: the second of the film the music
    comes in (07/10 Khủng Long Đỏ: the dance's own 34 s track under the dance only, from 16 s) — silent before it."""
    if end is not None and 0.5 < float(end) < video_duration:   # 07/10: a second music comes in at `end` — this one fades out there
        video_duration = float(end)
        fade = min(fade, END_FADE)                    # a short fade right at the hand-over, not a 1.5 s hole before the next song
    start = min(max(float(start or 0), 0.0), max(video_duration - 0.5, 0.0))
    if start:                            # the music's own timeline: breaths / silences planned on the film's move back by `start`
        breaths = [t - start for t in breaths if t - start > 0]
        music_off = [(a - start, b - start) for a, b in music_off if b - start > 0]
        video_duration = video_duration - start
    fade_out_start = max(video_duration - fade, 0)
    fade_in = min(fade, MUSIC_FADE_IN)   # 2A: a 1,5 s fade-in left the hook's first second silent
    loops = music_loops(music_len, video_duration)
    src = "[1:a]"
    pre = ""
    if loops:
        copies = "".join(f"[mc{i}]" for i in range(loops + 1))
        pre = f"[1:a]asplit={loops + 1}{copies};"
        joined = "[mc0]"
        for i in range(1, loops + 1):
            pre += f"{joined}[mc{i}]acrossfade=d={LOOP_XFADE}[ml{i}];"
            joined = f"[ml{i}]"
        src = joined
    music_chain = (f"{pre}{src}atrim=0:{video_duration},afade=t=in:d={fade_in},"
                   f"afade=t=out:st={fade_out_start}:d={fade},volume={volume}{breath_filter(breaths, music_off)}"
                   + (f",adelay={int(round(start * 1000))}:all=1" if start else "") + ",apad")  # apad: music shorter than video
    if has_audio:
        audio = f"{music_chain}[m];[0:a][m]amix=inputs=2:normalize=0:duration=first,{PEAK_LIMIT}[a]"
    else:
        audio = music_chain + f",{PEAK_LIMIT}[a]"
    return [ffmpeg, "-y", "-i", video, "-i", music, "-filter_complex", audio,
            "-map", "0:v", "-map", "[a]", "-c:v", "copy", *audio_codec, "-shortest", output]


MUSIC_FADE_IN = 0.3
END_FADE = 0.3          # the first music's fade where the second music comes in (07/10: 1.5 s left ~1 s of silence before the dance)
# The music dips 8–12 dB while someone speaks (the person chose 2026-09-26; editing.md E4). Measured on 3 real TTS lines of #7 under its
# chosen music: threshold 0.05 / ratio 3 → 9.4–11.5 dB (0.02 / 8, the setting before, pressed it 18.6–22.3 dB — nearly silent).
DUCK = "sidechaincompress=threshold=0.05:ratio=3:attack=20:release=400"


def build_extras_mix_cmd(video: str, extras: Sequence[dict], output: str, has_audio: bool,
                         ffmpeg: str = "ffmpeg", duck: bool = False) -> List[str]:
    """Lay extra audio (sound effects, voice-over) over the video at given start seconds and volumes.
    extras: [{"path", "start" (s), "volume" (0..2)}]. The video's own audio (music) is kept when has_audio."""
    if not extras:
        raise ValueError("no extra audio to mix")
    cmd = [ffmpeg, "-y", "-i", video]
    for e in extras:
        cmd += ["-i", e["path"]]
    parts, labels = [], ["[0:a]"] if has_audio else []
    for i, e in enumerate(extras):
        ms = max(int(round(float(e.get("start", 0)) * 1000)), 0)
        parts.append(f"[{i + 1}:a]adelay={ms}|{ms},volume={float(e.get('volume', 1.0))}[e{i}]")
        labels.append(f"[e{i}]")
    keys = [i for i, e in enumerate(extras) if e.get("key", True)]
    if duck and has_audio and keys:
        # the user (2026-09-25) asked for music that follows the cut: the voices press the music bed ([0:a]) down while they speak.
        # An ambience bed (key False, GĐ4 D5) plays all the time — it must not hold the music down for the whole scene
        others = [i for i in range(len(extras)) if i not in keys]
        voices = "".join(f"[e{i}]" for i in keys)
        parts.append(f"{voices}amix=inputs={len(keys)}:normalize=0:duration=longest,asplit=2[vk][vm]")
        # the key is padded with silence: sidechaincompress stops at the end of its SHORTER input, so the music ended with the last
        # line (trial #8, 2026-09-28: 79,6 s → end silent — the old delivery too, 80–83 s)
        parts.append(f"[vk]apad[vkp];[0:a][vkp]{DUCK}[bed]")
        rest = "".join(f"[e{i}]" for i in others)
        parts.append(f"[bed][vm]{rest}amix=inputs={2 + len(others)}:normalize=0:duration=longest,{PEAK_LIMIT},apad[a]")
    else:
        parts.append("".join(labels) + f"amix=inputs={len(labels)}:normalize=0:duration=longest,{PEAK_LIMIT},apad[a]")
    return cmd + ["-filter_complex", ";".join(parts), "-map", "0:v", "-map", "[a]", "-c:v", "copy",
                  *AAC, "-shortest", output]


def run(cmd: List[str]) -> None:
    proc = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if proc.returncode != 0:
        raise FFmpegError(proc.stderr[-2000:])


_AUDIO_STREAM = re.compile(r"Stream #\d+:\d+.*Audio:")


def has_audio(path: str) -> bool:
    """True when the file has an audio stream (read from `ffmpeg -i`)."""
    try:
        proc = subprocess.run([find_ffmpeg(), "-hide_banner", "-i", path], capture_output=True, text=True, encoding="utf-8", errors="replace")
    except (FFmpegNotFound, OSError):
        return False
    return bool(_AUDIO_STREAM.search(proc.stderr or ""))


# Loudness of a delivered file (knowledge/editor/editing.md E8, việc code D11 — measuring half). No platform publishes its LUFS (YouTube,
# TikTok, Meta); Spotify's official -14 LUFS / true peak under -1 dBTP is the common reference, AES TD1008 keeps -1 dBTP before a lossy
# encoder. The pipeline aims at -14 LUFS integrated, true peak -1,5 dBTP or lower (headroom for AAC).
LUFS_TARGET, LUFS_TOLERANCE, TRUE_PEAK_MAX = -14.0, 2.0, -1.5
_EBU = {"lufs": re.compile(r"I:\s*(-?[\d.]+|-inf)\s*LUFS"), "lra": re.compile(r"LRA:\s*(-?[\d.]+)\s*LU\b"),
        "true_peak_dbfs": re.compile(r"Peak:\s*(-?[\d.]+|-inf)\s*dBFS")}


def measure_loudness(path: str, ffmpeg: Optional[str] = None) -> Optional[dict]:
    """{"lufs", "lra", "true_peak_dbfs"} of a file's sound (EBU R128 meter of ffmpeg, true peak), None without sound / ffmpeg."""
    try:
        proc = subprocess.run([ffmpeg or find_ffmpeg(), "-hide_banner", "-nostats", "-i", path, "-map", "0:a:0",
                               "-af", "ebur128=peak=true", "-f", "null", "-"], capture_output=True, text=True, encoding="utf-8",
                              errors="replace")
    except (FFmpegNotFound, OSError):
        return None
    summary = (proc.stderr or "").rsplit("Summary:", 1)
    if proc.returncode != 0 or len(summary) < 2:
        return None
    out = {}
    for key, pat in _EBU.items():
        m = pat.search(summary[1])
        out[key] = (float("-inf") if m.group(1) == "-inf" else float(m.group(1))) if m else None
    return out


_LOUDNORM_JSON = re.compile(r"\{[^{}]*\"input_i\"[^{}]*\}", re.DOTALL)


def normalize_loudness(src: str, dst: str, ffmpeg: Optional[str] = None, target: float = LUFS_TARGET,
                       true_peak: float = TRUE_PEAK_MAX) -> dict:
    """Two-pass loudnorm (measure, then a LINEAR gain to the target — the mix is not re-compressed), video copied untouched.
    Returns the measurement after. ffmpeg's own default is I=-24 (broadcast), so the target is always given."""
    import json
    ff = ffmpeg or find_ffmpeg()
    spec = f"loudnorm=I={target:g}:TP={true_peak:g}:LRA=11"
    proc = subprocess.run([ff, "-hide_banner", "-nostats", "-i", src, "-map", "0:a:0", "-af", spec + ":print_format=json", "-f", "null",
                           "-"], capture_output=True, text=True, encoding="utf-8", errors="replace")
    m = _LOUDNORM_JSON.search(proc.stderr or "")
    if proc.returncode != 0 or not m:
        raise FFmpegError("không đo được độ to để chuẩn hóa: " + (proc.stderr or "")[-400:])
    first = json.loads(m.group(0))
    second = (f"{spec}:measured_I={first['input_i']}:measured_TP={first['input_tp']}:measured_LRA={first['input_lra']}"
              f":measured_thresh={first['input_thresh']}:offset={first['target_offset']}:linear=true:print_format=json,aresample=48000")
    proc = subprocess.run([ff, "-y", "-i", src, "-map", "0:v?", "-map", "0:a:0", "-c:v", "copy", "-af", second, *AAC,
                           "-movflags", "+faststart", dst], capture_output=True, text=True, encoding="utf-8", errors="replace")
    if proc.returncode != 0:
        raise FFmpegError((proc.stderr or "")[-600:])
    after = measure_loudness(dst, ff) or {}
    # loudnorm asked for LINEAR falls back to its dynamic mode (the mix is compressed) when the gain would push the true peak over
    # the ceiling — ffmpeg says which one it used ("normalization_type"); kept in the result, not hidden
    m2 = _LOUDNORM_JSON.search(proc.stderr or "")
    try:
        after["mode"] = json.loads(m2.group(0)).get("normalization_type") if m2 else None
    except ValueError:
        after["mode"] = None
    after["before"] = {"lufs": _num(first.get("input_i")), "lra": _num(first.get("input_lra")),
                       "true_peak_dbfs": _num(first.get("input_tp"))}   # the first pass: why a dynamic fallback happened (A21 / R4)
    return after


def _num(value) -> Optional[float]:
    try:
        v = float(value)
    except (TypeError, ValueError):
        return None
    return v if math.isfinite(v) else None


def _dynamic_reason(m: dict, target: float = LUFS_TARGET, lra_max: float = 11.0) -> str:
    """Why loudnorm had to compress instead of a linear gain — read from the first-pass measurement, not assumed (TON_DONG A21 / R4:
    the message used to blame the peaks even when ffmpeg could not measure the LRA at all)."""
    b = m.get("before") or {}
    if b.get("lra") is None or b.get("lufs") is None or (b.get("lra") == 0 and (b.get("lufs") or 0) < -60):
        return "ffmpeg không đo được dải động (LRA) của bản trộn — bản quá ngắn hoặc gần như im lặng — nên không tăng giảm tuyến tính được"
    if b["lra"] > lra_max:
        return f"dải động bản trộn LRA {b['lra']:g} LU rộng hơn {lra_max:g} LU — chênh giữa đoạn nhỏ và đoạn to quá lớn"
    if b.get("true_peak_dbfs") is not None and b["true_peak_dbfs"] + (target - b["lufs"]) > TRUE_PEAK_MAX:
        return (f"đỉnh quá cao so với độ to (đỉnh {b['true_peak_dbfs']:g} dBTP, cần tăng {target - b['lufs']:+.1f} dB) — hạ SFX/đỉnh rồi"
                " dựng lại")
    return "ffmpeg tự chuyển chế độ động (số đo lượt đầu không cho thấy lý do)"


def loudness_problems(m: Optional[dict]) -> List[str]:
    """What a person should know about a measured loudness (empty = in range)."""
    if not m or m.get("lufs") is None:
        return ["không đo được độ to (không có tiếng?)"]
    out = []
    if abs(m["lufs"] - LUFS_TARGET) > LUFS_TOLERANCE:
        out.append(f"độ to {m['lufs']:g} LUFS — mục tiêu {LUFS_TARGET:g} ± {LUFS_TOLERANCE:g} (nền tảng sẽ tự "
                   + ("hạ xuống" if m["lufs"] > LUFS_TARGET else "không nâng lên — nghe nhỏ hơn video bên cạnh") + ")")
    if m.get("mode") == "dynamic":
        out.append("chuẩn hóa phải NÉN bản trộn: " + _dynamic_reason(m) + " — nghe lại xem có bị bẹp không")
    if m.get("true_peak_dbfs") is not None and m["true_peak_dbfs"] > TRUE_PEAK_MAX:
        out.append(f"đỉnh thật {m['true_peak_dbfs']:g} dBTP > {TRUE_PEAK_MAX:g} — dễ rè sau khi nền tảng mã hóa lại")
    return out


_DURATION = re.compile(r"Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)")


_DURATION_CACHE: dict = {}


def probe_duration(path: str) -> Optional[float]:
    """Length in seconds read from `ffmpeg -i` (no ffprobe needed); None when it cannot be determined.
    Remembered per (file, size, modified time): the Dashboard asks for every clip on each redraw and each ask started an ffmpeg process."""
    try:
        st = os.stat(path)
        key = (os.path.abspath(path), st.st_size, st.st_mtime_ns)
    except OSError:
        key = None
    if key is not None and key in _DURATION_CACHE:
        return _DURATION_CACHE[key]
    value = _probe_duration(path)
    if key is not None and value is not None:
        if len(_DURATION_CACHE) > 2000:
            _DURATION_CACHE.clear()
        _DURATION_CACHE[key] = value
    return value


def _probe_duration(path: str) -> Optional[float]:
    try:
        proc = subprocess.run([find_ffmpeg(), "-hide_banner", "-i", path], capture_output=True, text=True, encoding="utf-8", errors="replace")
    except (FFmpegNotFound, OSError):
        return None
    m = _DURATION.search(proc.stderr or "")
    return int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3)) if m else None


def resize_to_size(src: str, dst: str, width: int, height: int, max_mb: Optional[float] = None, audio_kbps: int = 256,
                   fit: str = "pad") -> dict:
    """Bring the video to width x height. fit='pad' keeps the whole picture (black bars if the shape differs); fit='crop'
    fills the frame by cutting the edges (a vertical cut of a horizontal video, no bars). With max_mb: 2-pass H.264
    at a bitrate worked out from the target size, and re-encode at a lower bitrate until the file fits (max 4 tries).
    Returns {"path", "size_mb", "video_kbps", "attempts", "fits"}."""
    ffmpeg = find_ffmpeg()
    width, height = int(width) // 2 * 2, int(height) // 2 * 2          # H.264 needs even sizes
    if width < 64 or height < 64:
        raise ValueError("kích thước quá nhỏ")
    if fit == "crop":
        vf = f"scale={width}:{height}:force_original_aspect_ratio=increase,crop={width}:{height},setsar=1"
    else:
        vf = f"scale={width}:{height}:force_original_aspect_ratio=decrease,pad={width}:{height}:(ow-iw)/2:(oh-ih)/2,setsar=1"
    audio = ["-c:a", "aac", "-b:a", f"{audio_kbps}k"] if has_audio(src) else ["-an"]
    if not max_mb:
        run([ffmpeg, "-y", "-i", src, "-vf", vf, *_ENCODE, *audio, dst])
        return {"path": dst, "size_mb": os.path.getsize(dst) / 1e6, "video_kbps": None, "attempts": 1, "fits": True}
    seconds = probe_duration(src)
    if not seconds or seconds <= 0:
        raise ValueError("không đọc được độ dài video")
    kbps = max_mb * 8000 * 0.95 / seconds - (audio_kbps if audio[0] != "-an" else 0)   # 5% safety margin
    limit = max_mb * 1e6
    null = "NUL" if os.name == "nt" else "/dev/null"
    log_dir = tempfile.mkdtemp()
    for attempt in range(1, 5):
        if kbps < 50:
            raise ValueError(f"giới hạn {max_mb:g} MB quá nhỏ cho video dài {seconds:.0f}s ở kích thước này")
        log = os.path.join(log_dir, "pass")
        base = [ffmpeg, "-y", "-i", src, "-vf", vf, "-c:v", "libx264", "-b:v", f"{int(kbps)}k", "-pix_fmt", "yuv420p", *COLOR_TAGS,
                "-passlogfile", log]
        run(base + ["-pass", "1", "-an", "-f", "null", null])
        run(base + ["-pass", "2", *audio, "-movflags", "+faststart", dst])
        size = os.path.getsize(dst)
        if size <= limit:
            return {"path": dst, "size_mb": size / 1e6, "video_kbps": int(kbps), "attempts": attempt, "fits": True}
        kbps *= 0.85 * limit / size                                         # over the limit: aim lower and encode again
    return {"path": dst, "size_mb": os.path.getsize(dst) / 1e6, "video_kbps": int(kbps), "attempts": 4, "fits": False}


def _commit(staged: str, output: str) -> None:
    """Put a finished temp file under its final name (and its .srt next to it, written by subtitles.burn)."""
    if not os.path.exists(staged) or os.path.getsize(staged) == 0:
        raise FFmpegError(f"ffmpeg báo xong nhưng không có file {os.path.basename(output)} — giữ nguyên bản cũ")
    try:
        os.replace(staged, output)
    except PermissionError:
        raise FFmpegError(f"không ghi đè được {os.path.basename(output)} (file đang mở ở chương trình khác?) — giữ nguyên bản cũ") from None
    srt = os.path.splitext(staged)[0] + ".srt"
    if os.path.exists(srt):
        os.replace(srt, os.path.splitext(output)[0] + ".srt")


@contextlib.contextmanager
def atomic_output(output: str):
    """D6: yields a temp path next to `output` for ffmpeg to write; it replaces `output` only when the whole block worked. A failed
    or half-written render never sits under the final name (where the delivery status would take it for the newest version), and
    two renders of the same file never share a temp name."""
    root, ext = os.path.splitext(output)
    staged = f"{root}.part-{uuid.uuid4().hex[:8]}{ext or '.mp4'}"
    try:
        yield staged
        _commit(staged, output)
    except BaseException:
        for path in (staged, os.path.splitext(staged)[0] + ".srt"):
            try:
                os.remove(path)
            except OSError:
                pass
        raise


def render_final(clips: Sequence[str], output: str, durations: Optional[Sequence[float]] = None,
                 transition: str = "cut", fade: float = 1.0, music: Optional[str] = None,
                 music_volume: float = 0.6, extras: Optional[Sequence[dict]] = None,
                 keep_audio: bool = False, size=None, breaths: Sequence[float] = (),
                 music_off: Sequence[Tuple[float, float]] = (), music_start: float = 0.0, music_end: Optional[float] = None) -> str:
    """Concat clips (in scene order), optionally crossfade, mux music, then lay extra audio over it.
    keep_audio: keep the clips' own sound (needs an audio stream in EVERY clip; otherwise it is ignored and the
    result is silent before music/extras). size (W, H): the project frame — every clip is brought to it (clips from
    different models may differ in size). Written to a temp file first (atomic_output), so `output` is either the old
    file or the complete new one."""
    with atomic_output(output) as staged:
        _render_final(clips, staged, durations, transition, fade, music, music_volume, extras, keep_audio, size, breaths, music_off,
                      music_start, music_end)
    return output


def _render_final(clips, output, durations, transition, fade, music, music_volume, extras, keep_audio, size, breaths=(),
                  music_off=(), music_start=0.0, music_end=None) -> None:
    ffmpeg = find_ffmpeg()
    extras = list(extras or [])
    padded = []
    try:
        _render_steps(clips, output, durations, transition, fade, music, music_volume, extras, keep_audio, size, ffmpeg, padded,
                      breaths, music_off, music_start, music_end)
    finally:
        for tmp in padded:     # also when a later step failed (they used to stay behind)
            try:
                os.remove(tmp)
            except OSError:
                pass


def _render_steps(clips, output, durations, transition, fade, music, music_volume, extras, keep_audio, size, ffmpeg, padded,
                  breaths=(), music_off=(), music_start=0.0, music_end=None) -> None:
    if keep_audio and clips:
        # D4: a clip made without sound used to silence EVERY clip; it gets a silent track so the others keep theirs
        clips = list(clips)
        for i, c in enumerate(clips):
            if not has_audio(c):
                tmp = output + f".pad{i}.mp4"
                run([ffmpeg, "-y", "-i", c, "-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=44100",
                     "-shortest", "-c:v", "copy", *AAC, tmp])
                clips[i] = tmp
                padded.append(tmp)
    keep_audio = bool(keep_audio and clips and all(c in padded or has_audio(c) for c in clips))
    silent = output if music is None and not extras else output + ".silent.mp4"
    if transition in OVERLAP_STYLES:
        if durations is None:
            raise ValueError(f"durations required for {transition}")
        run(build_crossfade_cmd(clips, durations, silent, fade, ffmpeg, OVERLAP_STYLES[transition], keep_audio, size))
    elif keep_audio:
        run(build_concat_audio_cmd(clips, silent, ffmpeg, size))
    elif size:
        run(build_concat_scaled_cmd(clips, silent, size, ffmpeg))
    else:
        list_file = write_concat_list(clips)
        try:
            run(build_concat_cmd(list_file, silent, ffmpeg))
        finally:
            os.remove(list_file)
    current = silent
    if music is not None:
        if durations is None:
            raise ValueError("durations required to fit music")
        total = sum(durations) - (fade * (len(clips) - 1) if transition in OVERLAP_STYLES else 0)
        target = output + ".music.mkv" if extras else output          # mkv holds PCM: the mix below encodes AAC once
        try:
            run(build_mux_music_cmd(current, music, target, total, volume=music_volume, ffmpeg=ffmpeg,
                                    has_audio=keep_audio, breaths=breaths, music_off=music_off, music_len=probe_duration(music),
                                    audio_codec=PCM if extras else AAC, start=music_start, end=music_end))
        finally:
            os.remove(current)
        current = target
    if extras:
        try:
            run(build_extras_mix_cmd(current, extras, output, has_audio=music is not None or keep_audio, ffmpeg=ffmpeg,
                                     duck=music is not None and not keep_audio))
        finally:
            os.remove(current)


_SIZE = re.compile(r",\s*(\d{2,5})x(\d{2,5})[\s,\[]")


def probe_size(path: str):
    """(width, height) of a video from `ffmpeg -i`, or None."""
    try:
        proc = subprocess.run([find_ffmpeg(), "-hide_banner", "-i", path], capture_output=True, text=True, encoding="utf-8", errors="replace")
    except (FFmpegNotFound, OSError):
        return None
    for line in (proc.stderr or "").splitlines():
        if "Video:" in line:
            m = _SIZE.search(line)
            if m:
                return int(m.group(1)), int(m.group(2))
    return None


def overlay_still(video: str, png: str, output: str) -> str:
    """A transparent picture (same size as the video) laid over the whole video; sound copied as it is."""
    run([find_ffmpeg(), "-y", "-i", video, "-i", png, "-filter_complex", f"[0:v][1:v]overlay=0:0,{TO_YUV709}[v]",
         "-map", "[v]", "-map", "0:a?", *_ENCODE, "-c:a", "copy", output])
    return output


def append_still(video: str, still_png: str, seconds: float, output: str) -> str:
    """The video followed by a still picture (an end card) for `seconds`, with silence under the card. The picture is made with
    PIL beforehand (no drawtext: works without libfreetype and with any Vietnamese text)."""
    ffmpeg = find_ffmpeg()
    size = probe_size(video) or (1920, 1080)
    total = probe_duration(video) or 0
    fit = _fit(size)
    cmd = [ffmpeg, "-y", "-i", video, "-loop", "1", "-t", f"{seconds:.2f}", "-i", still_png,
           "-f", "lavfi", "-t", f"{seconds:.2f}", "-i", "anullsrc=r=48000:cl=stereo"]
    if has_audio(video):
        a0 = f"[0:a]{_A_NORM}[a0]"
    else:
        cmd += ["-f", "lavfi", "-t", f"{max(total, 0.1):.2f}", "-i", "anullsrc=r=48000:cl=stereo"]
        a0 = f"[3:a]{_A_NORM}[a0]"
    graph = ";".join([f"[0:v]{fit}[v0]", f"[1:v]{fit},{TO_YUV709}[v1]", a0, f"[2:a]{_A_NORM}[a1]",
                      "[v0][a0][v1][a1]concat=n=2:v=1:a=1[v][a]"])
    run(cmd + ["-filter_complex", graph, "-map", "[v]", "-map", "[a]", *_ENCODE, *AAC, output])
    return output
