import os
import re
import shutil
import subprocess
import tempfile
from typing import List, Optional, Sequence


class FFmpegNotFound(Exception):
    pass


class FFmpegError(Exception):
    pass


def find_ffmpeg() -> str:
    path = os.environ.get("FFMPEG_PATH") or shutil.which("ffmpeg")
    if not path:
        raise FFmpegNotFound("ffmpeg not found: install it or set FFMPEG_PATH")
    return path


_ENCODE = ["-c:v", "libx264", "-pix_fmt", "yuv420p", "-r", "24"]


def write_concat_list(clips: Sequence[str], directory: Optional[str] = None) -> str:
    fd, path = tempfile.mkstemp(suffix=".txt", dir=directory)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        for clip in clips:
            escaped = os.path.abspath(clip).replace("\\", "/").replace("'", "'\\''")
            f.write(f"file '{escaped}'\n")
    return path


def build_concat_cmd(list_file: str, output: str, ffmpeg: str = "ffmpeg") -> List[str]:
    return [ffmpeg, "-y", "-f", "concat", "-safe", "0", "-i", list_file, *_ENCODE, "-an", output]


OVERLAP_STYLES = {"crossfade": "fade", "dip_to_black": "fadeblack"}


_A_NORM = "aformat=sample_rates=48000:channel_layouts=stereo"  # clips from a model may differ in audio format


def _fit(size, mode: str = "pad") -> str:
    """Filter that brings any clip to exactly W x H: 'pad' keeps the whole picture (bars), 'crop' fills the frame."""
    w, h = int(size[0]) // 2 * 2, int(size[1]) // 2 * 2
    if mode == "crop":
        return f"scale={w}:{h}:force_original_aspect_ratio=increase,crop={w}:{h},setsar=1,fps=24"
    return f"scale={w}:{h}:force_original_aspect_ratio=decrease,pad={w}:{h}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=24"


def build_concat_scaled_cmd(clips: Sequence[str], output: str, size, ffmpeg: str = "ffmpeg") -> List[str]:
    """Hard cut without sound where clips may differ in size (e.g. two video models in one project): each clip is brought to
    the project frame first (the concat demuxer would break on mixed sizes)."""
    if not clips:
        raise ValueError("no clips")
    cmd = [ffmpeg, "-y"]
    parts = []
    for i, clip in enumerate(clips):
        cmd += ["-i", clip]
        parts.append(f"[{i}:v]{_fit(size)}[v{i}]")
    parts.append("".join(f"[v{i}]" for i in range(len(clips))) + f"concat=n={len(clips)}:v=1:a=0[v]")
    return cmd + ["-filter_complex", ";".join(parts), "-map", "[v]", *_ENCODE, "-an", output]


def build_concat_audio_cmd(clips: Sequence[str], output: str, ffmpeg: str = "ffmpeg", size=None) -> List[str]:
    """Hard cut that KEEPS each clip's own audio (e.g. dialogue generated by the video model). Every clip needs an
    audio stream. `size`: bring every clip to this frame first."""
    if not clips:
        raise ValueError("no clips")
    cmd = [ffmpeg, "-y"]
    parts = []
    for i, clip in enumerate(clips):
        cmd += ["-i", clip]
        parts.append(f"[{i}:v]{_fit(size) if size else 'setsar=1'}[v{i}];[{i}:a]{_A_NORM}[a{i}]")
    joined = "".join(f"[v{i}][a{i}]" for i in range(len(clips)))
    parts.append(f"{joined}concat=n={len(clips)}:v=1:a=1[v][a]")
    return cmd + ["-filter_complex", ";".join(parts), "-map", "[v]", "-map", "[a]", *_ENCODE, "-c:a", "aac", output]


def build_crossfade_cmd(clips: Sequence[str], durations: Sequence[float], output: str,
                        fade: float = 1.0, ffmpeg: str = "ffmpeg", style: str = "fade",
                        with_audio: bool = False, size=None) -> List[str]:
    if len(clips) != len(durations) or len(clips) < 2:
        raise ValueError("need >= 2 clips and one duration per clip")
    if any(d <= fade for d in durations):
        raise ValueError("every clip must be longer than the crossfade")
    cmd = [ffmpeg, "-y"]
    for clip in clips:
        cmd += ["-i", clip]
    parts = [f"[{i}:v]{_fit(size)}[s{i}]" for i in range(len(clips))] if size else []
    src = (lambda i: f"[s{i}]") if size else (lambda i: f"[{i}:v]")
    prev, elapsed = src(0), durations[0]
    for i in range(1, len(clips)):
        offset = round(elapsed - fade, 3)
        label = f"[v{i}]"
        parts.append(f"{prev}{src(i)}xfade=transition={style}:duration={fade}:offset={offset}{label}")
        prev = label
        elapsed += durations[i] - fade
    if not with_audio:
        return cmd + ["-filter_complex", ";".join(parts), "-map", prev, *_ENCODE, "-an", output]
    for i in range(len(clips)):
        parts.append(f"[{i}:a]{_A_NORM}[n{i}]")
    prev_a = "[n0]"
    for i in range(1, len(clips)):
        parts.append(f"{prev_a}[n{i}]acrossfade=d={fade}[x{i}]")
        prev_a = f"[x{i}]"
    return cmd + ["-filter_complex", ";".join(parts), "-map", prev, "-map", prev_a, *_ENCODE, "-c:a", "aac", output]


def build_mux_music_cmd(video: str, music: str, output: str, video_duration: float,
                        fade: float = 1.5, volume: float = 0.6, ffmpeg: str = "ffmpeg",
                        has_audio: bool = False) -> List[str]:
    """Music under the video. has_audio: the video already carries sound (dialogue): the music is MIXED with it
    instead of replacing it."""
    fade_out_start = max(video_duration - fade, 0)
    music_chain = (f"[1:a]atrim=0:{video_duration},afade=t=in:d={fade},"
                   f"afade=t=out:st={fade_out_start}:d={fade},volume={volume},apad")  # apad: music shorter than video
    if has_audio:
        audio = f"{music_chain}[m];[0:a][m]amix=inputs=2:normalize=0:duration=first[a]"
    else:
        audio = music_chain + "[a]"
    return [ffmpeg, "-y", "-i", video, "-i", music, "-filter_complex", audio,
            "-map", "0:v", "-map", "[a]", "-c:v", "copy", "-c:a", "aac", "-shortest", output]


def build_extras_mix_cmd(video: str, extras: Sequence[dict], output: str, has_audio: bool,
                         ffmpeg: str = "ffmpeg") -> List[str]:
    """Lay extra audio (sound effects, voice-over) over the video at given start seconds and volumes.
    extras: [{"path", "start" (s), "volume" (0..2)}]. The video's own audio (music) is kept when has_audio."""
    if not extras:
        raise ValueError("no extra audio to mix")
    cmd = [ffmpeg, "-y", "-i", video]
    for e in extras:
        cmd += ["-i", e["path"]]
    parts, labels = [], ["[0:a]"] if has_audio else []
    for i, e in enumerate(extras):
        ms = max(int(round(float(e.get("start", 0)) * 1000)), 0)
        parts.append(f"[{i + 1}:a]adelay={ms}|{ms},volume={float(e.get('volume', 1.0))}[e{i}]")
        labels.append(f"[e{i}]")
    parts.append("".join(labels) + f"amix=inputs={len(labels)}:normalize=0:duration=longest,apad[a]")
    return cmd + ["-filter_complex", ";".join(parts), "-map", "0:v", "-map", "[a]", "-c:v", "copy",
                  "-c:a", "aac", "-shortest", output]


def run(cmd: List[str]) -> None:
    proc = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if proc.returncode != 0:
        raise FFmpegError(proc.stderr[-2000:])


_AUDIO_STREAM = re.compile(r"Stream #\d+:\d+.*Audio:")


def has_audio(path: str) -> bool:
    """True when the file has an audio stream (read from `ffmpeg -i`)."""
    try:
        proc = subprocess.run([find_ffmpeg(), "-hide_banner", "-i", path], capture_output=True, text=True, encoding="utf-8", errors="replace")
    except (FFmpegNotFound, OSError):
        return False
    return bool(_AUDIO_STREAM.search(proc.stderr or ""))


_DURATION = re.compile(r"Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)")


def probe_duration(path: str) -> Optional[float]:
    """Length in seconds read from `ffmpeg -i` (no ffprobe needed); None when it cannot be determined."""
    try:
        proc = subprocess.run([find_ffmpeg(), "-hide_banner", "-i", path], capture_output=True, text=True, encoding="utf-8", errors="replace")
    except (FFmpegNotFound, OSError):
        return None
    m = _DURATION.search(proc.stderr or "")
    return int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3)) if m else None


def resize_to_size(src: str, dst: str, width: int, height: int, max_mb: Optional[float] = None, audio_kbps: int = 128,
                   fit: str = "pad") -> dict:
    """Bring the video to width x height. fit='pad' keeps the whole picture (black bars if the shape differs); fit='crop'
    fills the frame by cutting the edges (a vertical cut of a horizontal video, no bars). With max_mb: 2-pass H.264
    at a bitrate worked out from the target size, and re-encode at a lower bitrate until the file fits (max 4 tries).
    Returns {"path", "size_mb", "video_kbps", "attempts", "fits"}."""
    ffmpeg = find_ffmpeg()
    width, height = int(width) // 2 * 2, int(height) // 2 * 2          # H.264 needs even sizes
    if width < 64 or height < 64:
        raise ValueError("kích thước quá nhỏ")
    if fit == "crop":
        vf = f"scale={width}:{height}:force_original_aspect_ratio=increase,crop={width}:{height},setsar=1"
    else:
        vf = f"scale={width}:{height}:force_original_aspect_ratio=decrease,pad={width}:{height}:(ow-iw)/2:(oh-ih)/2,setsar=1"
    audio = ["-c:a", "aac", "-b:a", f"{audio_kbps}k"] if has_audio(src) else ["-an"]
    if not max_mb:
        run([ffmpeg, "-y", "-i", src, "-vf", vf, "-c:v", "libx264", "-crf", "23", "-pix_fmt", "yuv420p", *audio, dst])
        return {"path": dst, "size_mb": os.path.getsize(dst) / 1e6, "video_kbps": None, "attempts": 1, "fits": True}
    seconds = probe_duration(src)
    if not seconds or seconds <= 0:
        raise ValueError("không đọc được độ dài video")
    kbps = max_mb * 8000 * 0.95 / seconds - (audio_kbps if audio[0] != "-an" else 0)   # 5% safety margin
    limit = max_mb * 1e6
    null = "NUL" if os.name == "nt" else "/dev/null"
    log_dir = tempfile.mkdtemp()
    for attempt in range(1, 5):
        if kbps < 50:
            raise ValueError(f"giới hạn {max_mb:g} MB quá nhỏ cho video dài {seconds:.0f}s ở kích thước này")
        log = os.path.join(log_dir, "pass")
        base = [ffmpeg, "-y", "-i", src, "-vf", vf, "-c:v", "libx264", "-b:v", f"{int(kbps)}k", "-pix_fmt", "yuv420p", "-passlogfile", log]
        run(base + ["-pass", "1", "-an", "-f", "null", null])
        run(base + ["-pass", "2", *audio, dst])
        size = os.path.getsize(dst)
        if size <= limit:
            return {"path": dst, "size_mb": size / 1e6, "video_kbps": int(kbps), "attempts": attempt, "fits": True}
        kbps *= 0.85 * limit / size                                         # over the limit: aim lower and encode again
    return {"path": dst, "size_mb": os.path.getsize(dst) / 1e6, "video_kbps": int(kbps), "attempts": 4, "fits": False}


def render_final(clips: Sequence[str], output: str, durations: Optional[Sequence[float]] = None,
                 transition: str = "cut", fade: float = 1.0, music: Optional[str] = None,
                 music_volume: float = 0.6, extras: Optional[Sequence[dict]] = None,
                 keep_audio: bool = False, size=None) -> str:
    """Concat clips (in scene order), optionally crossfade, mux music, then lay extra audio over it.
    keep_audio: keep the clips' own sound (needs an audio stream in EVERY clip; otherwise it is ignored and the
    result is silent before music/extras). size (W, H): the project frame — every clip is brought to it (clips from
    different models may differ in size)."""
    ffmpeg = find_ffmpeg()
    extras = list(extras or [])
    padded = []
    if keep_audio and clips:
        # D4: a clip made without sound used to silence EVERY clip; it gets a silent track so the others keep theirs
        clips = list(clips)
        for i, c in enumerate(clips):
            if not has_audio(c):
                tmp = output + f".pad{i}.mp4"
                run([ffmpeg, "-y", "-i", c, "-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=44100",
                     "-shortest", "-c:v", "copy", "-c:a", "aac", tmp])
                clips[i] = tmp
                padded.append(tmp)
    keep_audio = bool(keep_audio and clips and all(c in padded or has_audio(c) for c in clips))
    silent = output if music is None and not extras else output + ".silent.mp4"
    if transition in OVERLAP_STYLES:
        if durations is None:
            raise ValueError(f"durations required for {transition}")
        run(build_crossfade_cmd(clips, durations, silent, fade, ffmpeg, OVERLAP_STYLES[transition], keep_audio, size))
    elif keep_audio:
        run(build_concat_audio_cmd(clips, silent, ffmpeg, size))
    elif size:
        run(build_concat_scaled_cmd(clips, silent, size, ffmpeg))
    else:
        list_file = write_concat_list(clips)
        try:
            run(build_concat_cmd(list_file, silent, ffmpeg))
        finally:
            os.remove(list_file)
    current = silent
    if music is not None:
        if durations is None:
            raise ValueError("durations required to fit music")
        total = sum(durations) - (fade * (len(clips) - 1) if transition in OVERLAP_STYLES else 0)
        target = output + ".music.mp4" if extras else output
        try:
            run(build_mux_music_cmd(current, music, target, total, volume=music_volume, ffmpeg=ffmpeg,
                                    has_audio=keep_audio))
        finally:
            os.remove(current)
        current = target
    if extras:
        try:
            run(build_extras_mix_cmd(current, extras, output, has_audio=music is not None or keep_audio, ffmpeg=ffmpeg))
        finally:
            os.remove(current)
    for tmp in padded:
        try:
            os.remove(tmp)
        except OSError:
            pass
    return output


_SIZE = re.compile(r",\s*(\d{2,5})x(\d{2,5})[\s,\[]")


def probe_size(path: str):
    """(width, height) of a video from `ffmpeg -i`, or None."""
    try:
        proc = subprocess.run([find_ffmpeg(), "-hide_banner", "-i", path], capture_output=True, text=True, encoding="utf-8", errors="replace")
    except (FFmpegNotFound, OSError):
        return None
    for line in (proc.stderr or "").splitlines():
        if "Video:" in line:
            m = _SIZE.search(line)
            if m:
                return int(m.group(1)), int(m.group(2))
    return None


def append_still(video: str, still_png: str, seconds: float, output: str) -> str:
    """The video followed by a still picture (an end card) for `seconds`, with silence under the card. The picture is made with
    PIL beforehand (no drawtext: works without libfreetype and with any Vietnamese text)."""
    ffmpeg = find_ffmpeg()
    size = probe_size(video) or (1920, 1080)
    total = probe_duration(video) or 0
    fit = _fit(size)
    cmd = [ffmpeg, "-y", "-i", video, "-loop", "1", "-t", f"{seconds:.2f}", "-i", still_png,
           "-f", "lavfi", "-t", f"{seconds:.2f}", "-i", "anullsrc=r=48000:cl=stereo"]
    if has_audio(video):
        a0 = f"[0:a]{_A_NORM}[a0]"
    else:
        cmd += ["-f", "lavfi", "-t", f"{max(total, 0.1):.2f}", "-i", "anullsrc=r=48000:cl=stereo"]
        a0 = f"[3:a]{_A_NORM}[a0]"
    graph = ";".join([f"[0:v]{fit}[v0]", f"[1:v]{fit},format=yuv420p[v1]", a0, f"[2:a]{_A_NORM}[a1]",
                      "[v0][a0][v1][a1]concat=n=2:v=1:a=1[v][a]"])
    run(cmd + ["-filter_complex", graph, "-map", "[v]", "-map", "[a]", *_ENCODE, "-c:a", "aac", output])
    return output
